# action.yml
name: 'PR Has Issues'
description: 'Checks for issues references in pull requests.'
inputs:
  repository:
    description: The
    required: true
  pr:
    description: The
    required: true
  pr:
    description: The
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.pr }}
